version: '3.8'

services:
  frontend:
    build: .
    container_name: legal-system-frontend
    ports:
      - "80:80"  # Фронтенд на порту 80
    restart: unless-stopped
    environment:
      - NGINX_HOST=bot.primelegal.kz
      - NGINX_PORT=80
    volumes:
      # Опционально: для логов nginx
      - ./logs:/var/log/nginx
    networks:
      - legal-network

  # API Backend (Nest.js) - добавьте когда будет готов
  # api:
  #   build: ./api
  #   container_name: legal-system-api
  #   ports:
  #     - "3003:3000"  # API на порту 3003
  #   restart: unless-stopped
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3000
  #   networks:
  #     - legal-network

networks:
  legal-network:
    driver: bridge