version: '3.8'

services:
  frontend:
    build: .
    container_name: legal-system-frontend
    ports:
      - "8081:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=bot.primelegal.kz
      - NGINX_PORT=80
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - lawyer_crm_lawyer-network

networks:
  lawyer_crm_lawyer-network:
    external: true
