version: '3.8'

services:
  frontend:
    build: .
    container_name: legal-system-frontend
    ports:
      - "8081:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=bot.primelegal.kz
      - NGINX_PORT=80
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - lawyer-network  # ← Измените на lawyer-network
    depends_on:
      - api  # ← Добавьте зависимость

  # Раскомментируйте API секцию или используйте external network
  api:
    external_name: legal-system-api
    networks:
      - lawyer-network

networks:
  lawyer-network:
    external: true  # ← Используем существующую сеть от API
